### ISSUE TITLE
Can't trade in GTS

### ISSUE THREAD

**Issue by chardrich** [mm201/pkmn-classic-framework#97] opened 2021-09-01 13:11 UTC
![IMG20210901210832](https://user-images.githubusercontent.com/16173179/131676961-10db3b79-ad97-457c-bf6b-43f4e8d0da5b.jpg)
I'm using Pokemon Black Version. I cannot trade with other trainers but can deposit my own Pokémon.1

**Comment by mm201** [comment] 2021-09-01 20:04
Dupe of #67

**Closed by mm201** 2021-09-01 20:04 UTC
